### ISSUE TITLE
panic on Compute

### ISSUE THREAD

**Issue by mdumandag** [puzpuzpuz/xsync#112]
Hi Andrey,

We were using the v2.5.1 for some time but upgraded to v3.0.1 recently.

After the upgrade, we hit the following panic:

```
panic: runtime error: index out of range [1678240084308591512] with length 0

goroutine 46 [running]:
github.com/puzpuzpuz/xsync/v3.(*MapOf[...]).doCompute(0x12d3540, 0x2e, 0xc0006e5f80, 0x0, 0x1)
	/home/runner/go/pkg/mod/github.com/puzpuzpuz/xsync/v3@v3.0.1/mapof.go:267 +0xa59
github.com/puzpuzpuz/xsync/v3.(*MapOf[...]).Compute(...)
	/home/runner/go/pkg/mod/github.com/puzpuzpuz/xsync/v3@v3.0.1/mapof.go:215
```

We haven't seen this panic for quite some time, and it occurred right after the upgrade, so it might be related to the recent changes.

The map has the following type, if it is going to help: `xsync.NewMapOfPresized[int64, someStruct](1000)`, where `someStruct` has two fields, one of the type `any` and one of the type `int`

**Comment by puzpuzpuz** [comment]
Hi Metin,

First of all, thanks for sharing the issue!

I think I know what might go wrong. Let me fix the bug and release v3.0.2.

**Comment by puzpuzpuz** [comment]
v3.0.2 is out.
